In [2]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

# Data handling
from torch.utils.data import DataLoader, Dataset
from torchvision import datasets, transforms
import torchvision
import torchvision.transforms as T

# Utility libraries
import numpy as np
import matplotlib.pyplot as plt
from tqdm import tqdm
import random


## Tensor

In [3]:
#Tensor is a spcialized multi-dimesinal array for mathematical and computaional efficiency
# 5D Tesnor video data 

#why are tensor useful ?
#1.Mathematical operations
#2.Efficeint Computation 
#3.Efficient Computation


#where are tensor used in Deep learning ?

#1 Data storage 
#2 Weight and Biases
#3 Matrix oepration 

# 4 Training process



In [5]:
import torch
print(torch.__version__)

2.5.1


In [6]:
import torch

# Check if MPS is available
if torch.backends.mps.is_available():
    # Check if PyTorch was built with MPS support
    if torch.backends.mps.is_built():
        print("PyTorch MPS backend is available and built!")
        # Set the device
        mps_device = torch.device("mps")
        print(f"Using device: {mps_device}")

        # Example: Create a tensor on the MPS device
        try:
            x = torch.ones(5, device=mps_device)
            print("Successfully created a tensor on the MPS device:")
            print(x)
        except Exception as e:
            print(f"Failed to create tensor on MPS device: {e}")

    else:
        print("MPS not available because the current PyTorch install was not built with MPS enabled.")

else:
    # This might mean the macOS version is too old (needs 12.3+)
    # or the hardware doesn't support MPS.
    print("MPS not available. Check your macOS version (12.3+ needed) and hardware.")
    print("Falling back to CPU.")
    cpu_device = torch.device("cpu")
    print(f"Using device: {cpu_device}")

PyTorch MPS backend is available and built!
Using device: mps
Successfully created a tensor on the MPS device:
tensor([1., 1., 1., 1., 1.], device='mps:0')


## Creating a Tensor

In [8]:
#using empty 
a=torch.empty(2,3)

In [10]:
#check type
type(a)


torch.Tensor

In [11]:
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [12]:
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [13]:
torch.rand(3,3)

tensor([[0.7534, 0.1258, 0.5249],
        [0.6063, 0.7897, 0.8261],
        [0.7403, 0.0518, 0.5476]])

In [15]:
torch.manual_seed(100)
torch.rand(3,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539],
        [0.2627, 0.0428, 0.2080]])

## Tensor Shapes

In [16]:
x=torch.tensor([[1,2,3],[4,5,6]])
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [17]:
x.shape

torch.Size([2, 3])

In [19]:
torch.empty_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [25]:
torch.rand_like(x,dtype=torch.float32)

tensor([[0.1180, 0.1217, 0.7356],
        [0.7118, 0.7876, 0.4183]])

## Tensor Data Types

In [21]:
x.dtype

torch.int64

In [23]:
#assing data type
torch.tensor([1.0,2.0,3.0],dtype=torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

### matehmatical operation

In [26]:
x+2

tensor([[3, 4, 5],
        [6, 7, 8]])

In [27]:
x-2

tensor([[-1,  0,  1],
        [ 2,  3,  4]])

In [28]:
x*3

tensor([[ 3,  6,  9],
        [12, 15, 18]])

In [29]:
x/3

tensor([[0.3333, 0.6667, 1.0000],
        [1.3333, 1.6667, 2.0000]])

In [30]:
x**2

tensor([[ 1,  4,  9],
        [16, 25, 36]])

In [31]:
# elment wise operations

a=torch.rand(2,3)
b=torch.rand(2,3)

In [32]:
print(a)
print(b)

tensor([[0.9014, 0.9969, 0.7565],
        [0.2239, 0.3023, 0.1784]])
tensor([[0.8238, 0.5557, 0.9770],
        [0.4440, 0.9478, 0.7445]])


In [33]:
a+b

tensor([[1.7253, 1.5526, 1.7335],
        [0.6679, 1.2502, 0.9229]])

In [34]:
a-b

tensor([[ 0.0776,  0.4411, -0.2205],
        [-0.2201, -0.6455, -0.5661]])

In [35]:
a*b

tensor([[0.7426, 0.5540, 0.7391],
        [0.0994, 0.2866, 0.1328]])

In [36]:
a**b

tensor([[0.9180, 0.9983, 0.7614],
        [0.5145, 0.3218, 0.2771]])

In [37]:
a/b

tensor([[1.0942, 1.7938, 0.7743],
        [0.5042, 0.3190, 0.2397]])

## Reduction operation

In [46]:
e=torch.randint(size=(2,3),low=0,high=10,dtype=torch.float32)
e

tensor([[9., 5., 7.],
        [3., 9., 4.]])

In [47]:
torch.sum(e)


tensor(37.)

In [48]:
torch.sum(e,dim=0)

tensor([12., 14., 11.])

In [49]:
torch.mean(e)

tensor(6.1667)

In [50]:
torch.prod(e)

tensor(34020.)

## Matrix oepration

In [51]:
f=torch.randint(size=(2,3),low=0,high=10)
g=torch.randint(size=(3,2),low=0,high=10)


In [52]:
print(f)
print(g)

tensor([[0, 5, 7],
        [5, 9, 9]])
tensor([[7, 5],
        [9, 8],
        [9, 7]])


In [53]:
#matrix multi
torch.matmul(f,g)

tensor([[108,  89],
        [197, 160]])

In [54]:
h=torch.randint(size=(3,3),low=0,high=10,dtype=torch.float32)

## inpalce operation

In [57]:
m=torch.rand(2,3)
n=torch.rand(2,3)

In [58]:
print(m)
print(n)

tensor([[0.3039, 0.6726, 0.5740],
        [0.9233, 0.9178, 0.7590]])
tensor([[0.7775, 0.6179, 0.3379],
        [0.2170, 0.9454, 0.7116]])


In [59]:
m.add_(n)

tensor([[1.0814, 1.2905, 0.9118],
        [1.1403, 1.8632, 1.4706]])

In [60]:
m

tensor([[1.0814, 1.2905, 0.9118],
        [1.1403, 1.8632, 1.4706]])

In [61]:
n

tensor([[0.7775, 0.6179, 0.3379],
        [0.2170, 0.9454, 0.7116]])

## Copying a Tensor

In [62]:
a=torch.rand(2,3)

In [63]:
b=a

In [64]:
b

tensor([[0.1157, 0.6574, 0.3451],
        [0.0453, 0.9798, 0.5548]])

In [65]:
a[0][0]=0

In [66]:
a

tensor([[0.0000, 0.6574, 0.3451],
        [0.0453, 0.9798, 0.5548]])

In [67]:
b

tensor([[0.0000, 0.6574, 0.3451],
        [0.0453, 0.9798, 0.5548]])

In [68]:
id(a)

13072522640

In [69]:
id(b)

13072522640

In [70]:
b=a.clone()

In [71]:
a

tensor([[0.0000, 0.6574, 0.3451],
        [0.0453, 0.9798, 0.5548]])

In [72]:
b

tensor([[0.0000, 0.6574, 0.3451],
        [0.0453, 0.9798, 0.5548]])

In [73]:
a[0][0]=10

In [74]:
a

tensor([[10.0000,  0.6574,  0.3451],
        [ 0.0453,  0.9798,  0.5548]])

In [75]:
b

tensor([[0.0000, 0.6574, 0.3451],
        [0.0453, 0.9798, 0.5548]])

## Tesnor operation on GPU 

In [76]:
device=torch.device('mps')

In [77]:
#creating a new tensor on gpu

torch.rand((2,3),device=device)

tensor([[0.4643, 0.8532, 0.4872],
        [0.4602, 0.4261, 0.0968]], device='mps:0')

In [78]:
# moving an existinf tenosr to gpu 
a

tensor([[10.0000,  0.6574,  0.3451],
        [ 0.0453,  0.9798,  0.5548]])

In [79]:
a.to(device)

tensor([[10.0000,  0.6574,  0.3451],
        [ 0.0453,  0.9798,  0.5548]], device='mps:0')

In [80]:
b+5

tensor([[5.0000, 5.6574, 5.3451],
        [5.0453, 5.9798, 5.5548]])

In [81]:
a+5

tensor([[15.0000,  5.6574,  5.3451],
        [ 5.0453,  5.9798,  5.5548]])

In [82]:
import torch
import time
import platform

def benchmark_matmul(device_name, matrix_size, iterations):
    """
    Benchmarks matrix multiplication on a specified device.

    Args:
        device_name (str): 'cpu' or 'mps'.
        matrix_size (int): Dimension of the square matrices (e.g., 4096).
        iterations (int): Number of times to repeat the multiplication.

    Returns:
        float: Average time per matrix multiplication in milliseconds.
               Returns None if the device is 'mps' but not available.
    """
    print(f"\n--- Benchmarking on {device_name.upper()} ---")
    
    # Check if MPS device is requested and available
    if device_name == "mps":
        if not torch.backends.mps.is_available():
            print("MPS device not found or not supported on this system/PyTorch build.")
            print("Skipping MPS benchmark.")
            return None
        if not torch.backends.mps.is_built():
             print("Current PyTorch install was not built with MPS enabled.")
             print("Skipping MPS benchmark.")
             return None
        # Additional check for macOS version compatibility might be useful
        # though is_available() generally covers it.

    try:
        # Set the device
        device = torch.device(device_name)

        # Create random matrices directly on the target device
        # Using float32 as it's commonly used and well-supported
        a = torch.randn(matrix_size, matrix_size, device=device, dtype=torch.float32)
        b = torch.randn(matrix_size, matrix_size, device=device, dtype=torch.float32)

        print(f"Matrix Size: {matrix_size}x{matrix_size}")
        print(f"Iterations: {iterations}")
        print(f"Data Type: {a.dtype}")

        # Warm-up: Perform one multiplication before timing
        # This helps account for initialization overhead (especially on GPU)
        _ = torch.matmul(a, b)

        # --- Synchronization is crucial for accurate GPU timing ---
        if device.type == 'mps':
            # Wait for the warm-up operation to complete on the GPU
            torch.mps.synchronize()

        # Start timer
        start_time = time.perf_counter()

        # Perform the multiplication multiple times
        for _ in range(iterations):
            _ = torch.matmul(a, b)

        # --- Synchronization before stopping timer ---
        if device.type == 'mps':
            # Wait for all queued GPU operations to finish
            torch.mps.synchronize()

        # Stop timer
        end_time = time.perf_counter()

        # Calculate times
        total_time = end_time - start_time
        avg_time_sec = total_time / iterations
        avg_time_ms = avg_time_sec * 1000

        print(f"Total time for {iterations} iterations: {total_time:.4f} seconds")
        print(f"Average time per multiplication: {avg_time_ms:.4f} milliseconds")

        # Clean up memory (optional, but good practice)
        del a, b
        if device.type == 'mps':
            torch.mps.empty_cache()

        return avg_time_ms

    except Exception as e:
        print(f"An error occurred during the {device_name.upper()} benchmark: {e}")
        # If it's an MPS memory error, suggest smaller size
        if device_name == 'mps' and isinstance(e, RuntimeError) and 'allocated' in str(e).lower():
             print("This might be an Out-of-Memory error on the GPU. Try a smaller 'matrix_size'.")
        return None

# --- Configuration ---
matrix_size = 4096  # Dimension of the square matrix (e.g., 1024, 2048, 4096)
                    # Adjust based on your system's RAM/VRAM. Start smaller if unsure.
iterations = 50     # Number of multiplications to average over (more iterations give smoother results)

# --- Run Benchmarks ---
print("Starting Matrix Multiplication Benchmark...")
print(f"PyTorch Version: {torch.__version__}")
print(f"Platform: {platform.system()} {platform.release()} ({platform.machine()})")


# Benchmark CPU
cpu_avg_time = benchmark_matmul('cpu', matrix_size, iterations)

# Benchmark MPS (Apple Silicon GPU)
mps_avg_time = benchmark_matmul('mps', matrix_size, iterations)

# --- Comparison ---
print("\n--- Results Summary ---")
if cpu_avg_time is not None:
    print(f"CPU Average Time: {cpu_avg_time:.4f} ms")
if mps_avg_time is not None:
    print(f"MPS Average Time: {mps_avg_time:.4f} ms")

if cpu_avg_time is not None and mps_avg_time is not None:
    speedup = cpu_avg_time / mps_avg_time
    print(f"\nGPU (MPS) is approximately {speedup:.2f} times faster than CPU for this task.")
elif mps_avg_time is None and cpu_avg_time is not None:
    print("\nCould not perform MPS benchmark.")
else:
    print("\nCould not perform benchmarks.")

Starting Matrix Multiplication Benchmark...
PyTorch Version: 2.5.1
Platform: Darwin 24.4.0 (arm64)

--- Benchmarking on CPU ---
Matrix Size: 4096x4096
Iterations: 50
Data Type: torch.float32
Total time for 50 iterations: 4.4706 seconds
Average time per multiplication: 89.4111 milliseconds

--- Benchmarking on MPS ---
Matrix Size: 4096x4096
Iterations: 50
Data Type: torch.float32
Total time for 50 iterations: 2.0341 seconds
Average time per multiplication: 40.6817 milliseconds

--- Results Summary ---
CPU Average Time: 89.4111 ms
MPS Average Time: 40.6817 ms

GPU (MPS) is approximately 2.20 times faster than CPU for this task.


## Reshaping tesnors


In [84]:
a=torch.ones(4,4)
a

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [85]:
a.reshape(2,2,2,2)

tensor([[[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]]])

In [86]:
a.flatten()

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [88]:
c=torch.rand(226,226,3)

In [90]:
c.unsqueeze(0).shape

torch.Size([1, 226, 226, 3])